name: Treasure Workflow Deploy

on: 
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Treasure Workflow
      uses: treasuredataps/td_wf_deploy@0.0.1
      with:
        # Treasure Workflow API Endpoint
        td_wf_endpoint: https://api-workflow.treasuredata.com
        # Treasure Data Master API
        td_master_apikey: ${{ secrets.td_master_apikey }}
        # Treasure Workflow Project Name 
        td_wf_project_name: raman_cicd_test