name: Treasure Workflow Deploy

on: 
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: "td wf push"
      uses: treasuredataps/tdw-actions@master
      with:
          td_master_apikey: ${{ secrets.td_master_apikey }}
          td_wf_project_names: raman_cicd_test 
          github_path: e
